// Code generated by protoc-gen-go. DO NOT EDIT.
// source: abstract.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JsonRequest struct {
	JsonData             string   `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonRequest) Reset()         { *m = JsonRequest{} }
func (m *JsonRequest) String() string { return proto.CompactTextString(m) }
func (*JsonRequest) ProtoMessage()    {}
func (*JsonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0be73c776a127c, []int{0}
}

func (m *JsonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonRequest.Unmarshal(m, b)
}
func (m *JsonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonRequest.Marshal(b, m, deterministic)
}
func (m *JsonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonRequest.Merge(m, src)
}
func (m *JsonRequest) XXX_Size() int {
	return xxx_messageInfo_JsonRequest.Size(m)
}
func (m *JsonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JsonRequest proto.InternalMessageInfo

func (m *JsonRequest) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type JsonResponse struct {
	ResponseMessage      string   `protobuf:"bytes,1,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonResponse) Reset()         { *m = JsonResponse{} }
func (m *JsonResponse) String() string { return proto.CompactTextString(m) }
func (*JsonResponse) ProtoMessage()    {}
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0be73c776a127c, []int{1}
}

func (m *JsonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonResponse.Unmarshal(m, b)
}
func (m *JsonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonResponse.Marshal(b, m, deterministic)
}
func (m *JsonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonResponse.Merge(m, src)
}
func (m *JsonResponse) XXX_Size() int {
	return xxx_messageInfo_JsonResponse.Size(m)
}
func (m *JsonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JsonResponse proto.InternalMessageInfo

func (m *JsonResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*JsonRequest)(nil), "abstract.JsonRequest")
	proto.RegisterType((*JsonResponse)(nil), "abstract.JsonResponse")
}

func init() {
	proto.RegisterFile("abstract.proto", fileDescriptor_ed0be73c776a127c)
}

var fileDescriptor_ed0be73c776a127c = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4c, 0x2a, 0x2e,
	0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xb4,
	0xb8, 0xb8, 0xbd, 0x8a, 0xf3, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb9,
	0x38, 0xb3, 0x8a, 0xf3, 0xf3, 0xe2, 0x53, 0x12, 0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x38, 0x40, 0x02, 0x2e, 0x89, 0x25, 0x89, 0x4a, 0x96, 0x5c, 0x3c, 0x10, 0xb5, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x9a, 0x5c, 0x02, 0x45, 0x50, 0x76, 0x7c, 0x6e, 0x6a, 0x71, 0x71,
	0x62, 0x7a, 0x2a, 0x54, 0x0f, 0x3f, 0x4c, 0xdc, 0x17, 0x22, 0x6c, 0xe4, 0xc1, 0xc5, 0xee, 0x97,
	0x5a, 0x52, 0x9e, 0x5f, 0x94, 0x2d, 0x64, 0xcb, 0xc5, 0x13, 0x9c, 0x9a, 0x97, 0xe2, 0x05, 0x35,
	0x55, 0x48, 0x54, 0x0f, 0xee, 0x38, 0x24, 0x97, 0x48, 0x89, 0xa1, 0x0b, 0x43, 0x0c, 0x74, 0x52,
	0x89, 0x52, 0x4a, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x4e, 0xce,
	0x2f, 0x29, 0xa9, 0xd4, 0x4d, 0xd6, 0x87, 0x29, 0xd6, 0x07, 0x7b, 0x30, 0x89, 0x0d, 0x4c, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xd4, 0x0f, 0x2a, 0xf9, 0x00, 0x00, 0x00,
}
